[package]
name = "retrieve_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "retrieve_rs"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.14.0"
pyo3 = { version = "0.21", features = ["extension-module"] }
rand = "0.10.0"
